create table users
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint users_version_check
            check (version > 0)
        constraint users_version_check1
            check (version >= 1),
    birth_date   timestamp(6)                           not null,
    email        varchar(50)                            not null,
    name         varchar(50)                            not null,
    surname      varchar(50)                            not null
);

comment on column users.id is 'Identifier';

comment on column users.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column users.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column users.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column users.birth_date is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column users.email is 'The email address of the user. Must be a valid email and between 4 and 50 characters.';

comment on column users.name is 'Name of user, will be used in column card_info.holder';

comment on column users.surname is 'Name of user, will be used in column card_info.holder';



create index idx_app_user_email on users (email);