create table app_user
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint app_user_version_check
            check (version > 0)
        constraint app_user_version_check1
            check (version >= 1),
    birth_date   timestamp(6)                           not null,
    email        varchar(50)                            not null,
    name         varchar(50)                            not null,
    surname      varchar(50)                            not null
);

comment on column app_user.id is 'Identifier';

comment on column app_user.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column app_user.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column app_user.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column app_user.birth_date is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column app_user.email is 'The email address of the user. Must be a valid email and between 4 and 50 characters.';

comment on column app_user.name is 'Name of user, will be used in column card_info.holder';

comment on column app_user.surname is 'Name of user, will be used in column card_info.holder';

alter table app_user
    owner to "user-postgres";

create index idx_app_user_email on app_user (email);