create table IF NOT EXISTS card_info
(
    id              bigint generated by default as identity
        primary key,
    created_dttm    timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at      timestamp(6) default CURRENT_TIMESTAMP not null,
    version         bigint       default 1                 not null
        constraint card_info_version_check
            check (version > 0)
        constraint card_info_version_check1
            check (version >= 1),
    expiration_date timestamp(6)                           not null,
    holder          varchar(255)                           not null,
    number          varchar(16)                            not null,
    user_id         bigint                                 not null
        constraint fk_card_user
            references users
);

comment on column card_info.id is 'Identifier';

comment on column card_info.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column card_info.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column card_info.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column card_info.expiration_date is 'Card expiration date';

comment on column card_info.holder is 'Name of card holder';

comment on column card_info.number is '16-digits card number';

comment on column card_info.user_id is 'Reference to card holder';



create index idx_card_info_user_id on card_info (user_id);
create index idx_card_info_number on card_info (number);